
[dodecl]
  project-name = "fancy project"

[[resource]]
  type = "compute.v2.droplet"
  name = "lb"

  [resource.properties]
    image = "ubuntu-16-04-x64"
    size = "2gb"
    keys = [
  "104064",
]
    region = "nyc1"
    count = 2

[[resource]]
  type = "compute.v2.floating-ip"

  [resource.properties]
    region = "nyc1"
